Dev
VictorMosolea/food-ordering pull request #2
Opened 2019-11-03 20:30 UTC by VictorMosolea

2019-11-03 20:31 UTC, VictorMosolea commented
Accidentally committed 3 times. Sorry for that

2019-11-04 21:00 UTC, Ranapop requested changes
See code comments

2019-11-04 21:00 UTC, Ranapop commented on main.c
> +#include "userData&Order.h"
that '&' is a sign maybe you should split the functionality

2019-11-04 21:00 UTC, Ranapop commented on printOptions.c
> +        if (drinkPrices[i - 1] > 0) printf(" %d\n", drinkPrices[i - 1]);
what are you doing here? looks avoidable

2019-11-04 21:00 UTC, Ranapop commented on userData&Order.c
> +#define MAX_FOOD_NAME 10
you have them defined in multiple files. You could extract them in a file constants.h or something...

2019-11-04 21:00 UTC, Ranapop commented on userData&Order.c
> +                    int specialityChoice, char YesNo[][4], int prices[MAX_NR_FOODS][MAX_NR_OF_PRICES], char drink[][MAX_DRINK_NAME],
you are sending more data then needed... you don't have to send the whole food options, just the chosen food.. same applies for other parameters. If you send only the data you need, you might also have less parameters (cause you're having quite a lot now)

2019-11-06 15:40 UTC, VictorMosolea commented
-split the functionality 
-stored all the constants in a file
-got rid of unnecessary parameters in functions

2019-11-06 22:17 UTC, Ranapop requested changes
see code comments

2019-11-06 22:17 UTC, Ranapop commented on main.c
> +#include "getUserData.h"
would not start a file name with a verb. File names are usually nouns

2019-11-06 22:17 UTC, Ranapop commented on main.c
> +#include "printOrder.h"
same here

2019-11-06 22:17 UTC, Ranapop commented on main.c
>  #include "printOptions.h"
same here (use noun)

2019-11-06 22:17 UTC, Ranapop commented on main.c
> +int cutleryChoice;
why global?

2019-11-06 22:17 UTC, Ranapop commented on main.c
>          if (foodsChoice == 3)
what 3?

2019-11-07 10:26 UTC, VictorMosolea commented
-renamed files in order for them to not contain verbs
-replaced "3" with a more general case: "nrOfFoods" and did this in multiple places
-variables are now declared in main and the main function has less than 60 lines of code

2019-11-18 00:17 UTC, merged